version: '3.3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile-spring
    networks:
      - my-net
    ports:
      - 8080:8080
  influxdb:
    build:
      context: .
      dockerfile: Dockerfile-influxdb
    networks:
      - my-net
    ports:
      - 8086:8086

networks:
  my-net:
    driver: bridge